[package]
name = "outro_08"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.9", features = ["default", "macros"] }
axum-test = "21.0.0"
serde = { version = "1.0.229", features = ["derive", "rc"] }
tokio = { version = "1.53.1", features = ["full"] }
thiserror = "2.0.19"
ticket_fields = { path = "../../../helpers/ticket_fields" }
serde_json = "1.0.151"
